- name: "Create logs folder"
  become: yes
  file:
    path: "/var/log/enduro/"
    owner: "{{ enduro_system_user }}"
    group: "{{ enduro_system_group }}"
    mode: 0755
    state: "directory"

- name: "Configure rsyslog"
  template:
    src: templates/rsyslog.conf.j2
    dest: /etc/rsyslog.d/50-{{ service }}.conf
  notify: restart rsyslog

- name: "Configure log rotation"
  template:
    src: templates/logrotate.conf.j2
    dest: /etc/logrotate.d/{{ service }}
