---
- name: Copy the enduro-am-worker systemd service file
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/enduro-am-worker.service
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - templates/{{ inventory_hostname }}/enduro-am-worker.service.j2
    - templates/enduro-am-worker.service.j2
  notify: restart enduro-am-worker

- name: Configure logging
  block:
    - include_tasks: configure-logging.yml
      vars:
        service: "enduro-am-worker"
        conf_files_name: "enduro-am-worker"
        logfile: "/var/log/enduro/enduro-am-worker.log"
        order: "50"
  when: enduro_use_syslog|bool
