---

- name: "Create preprocessing shared folder"
  become: yes
  file:
    path: "/var/lib/enduro/preprocessing"
    owner: "{{ enduro_system_user }}"
    group: "{{ enduro_system_group }}"
    mode: 0755
    state: "directory"

- name: Copy the preprocessing worker config file
  template:
    src: "{{ item }}"
    dest: /etc/preprocessing-worker.toml
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - templates/{{ inventory_hostname }}/preprocessing-worker.toml.j2
    - templates/preprocessing-worker.toml.j2
  notify: restart preprocessing-worker

- name: Copy the allowed formats config file
  template:
    src: "{{ item }}"
    dest: /etc/allowed_formats.csv
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - templates/{{ inventory_hostname }}/allowed_formats.csv
    - templates/allowed_formats.csv.j2
  notify: restart preprocessing-worker


