---
- name: Copy the enduro systemd service file
  template:
    src: templates/enduro.service.j2
    dest: /etc/systemd/system/enduro.service
    owner: root
    group: root
    mode: 0644
  notify: restart enduro

- name: Copy the enduro config file
  template:
    src: "{{ enduro_config_file }}"
    dest: /etc/enduro.toml
    owner: root
    group: root
    mode: 0644
  when: not enduro_systemd_credentials|bool
  notify: restart enduro

- name: Copy the PREMIS XSD file
  template:
    src: "{{ item }}"
    dest: /etc/premis.xsd
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - templates/{{ inventory_hostname }}/premis.xsd.j2
    - templates/premis.xsd.j2
- name: Use systemd credentials
  block:
    - include_tasks: systemd-creds.yml
      vars:
        service: "enduro"
        secret_name: "enduro.toml"
        secret_file: "{{ enduro_config_file }}"
    - include_tasks: systemd-creds.yml
      vars:
        service: "enduro-am-worker"
        secret_name: "enduro.toml"
        secret_file: "{{ enduro_config_file }}"
  
    - name: "Remove cleartext configuration file"
      file:
        path: "/etc/enduro.toml"
        state: absent
  when: enduro_systemd_credentials|bool


- name: "Create pipeline Transferdir path directories when using watched filesystem"
  become: yes
  file:
    path: "{{ item.transfer_dir }}"
    state: "directory"
    owner: "{{ enduro_system_user }}"
    group: "{{ enduro_system_group }}"
    mode: 0755
  loop: "{{ enduro_pipelines }}"
  when:
    - enduro_pipelines|length > 0
    - enduro_create_pipeline_transfer_dir|bool

- name: Configure logging
  block:
    - include_tasks: configure-logging.yml
      vars:
        service: "enduro"
        logfile: "/var/log/enduro/enduro.log"
        order: "50"
  when: enduro_use_syslog|bool

