---
- name: Copy the enduro systemd service file
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/enduro.service
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - templates/{{ inventory_hostname }}/enduro.service.j2
    - templates/enduro.service.j2
  notify: restart enduro

- name: Copy the PREMIS XSD file
  template:
    src: "{{ item }}"
    dest: /etc/premis.xsd
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - templates/{{ inventory_hostname }}/premis.xsd.j2
    - templates/premis.xsd.j2

- name: Copy the enduro config file
  template:
    src: "{{ item }}"
    dest: /etc/enduro.toml
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - templates/{{ inventory_hostname }}/enduro.toml.j2
    - templates/enduro.toml.j2
  notify: restart enduro

- name: "Configure enduro_storage SS backend"
  mysql_query:
    login_db: "{{ enduro_storage_db_name }}"
    login_user: "{{ enduro_storage_db_user }}"
    login_password: "{{ enduro_storage_db_pass }}"
    query: INSERT IGNORE INTO enduro_storage.location (name, description, source, purpose, uuid, created_at, config) VALUES ('amss', '', 'amss', 'aip_store', %(location_uuid)s, NOW(), %(ss_config)s )
    named_args:
      ss_config: "{{ enduro_storage_config | to_json }}"
      location_uuid: "{{ enduro_storage_location_uuid }}"
  when:
    - "enduro_storage_config is defined"

- name: "Create pipeline Transferdir path directories when using watched filesystem"
  become: yes
  file:
    path: "{{ item.transfer_dir }}"
    state: "directory"
    owner: "{{ enduro_system_user }}"
    group: "{{ enduro_system_group }}"
    mode: 0755
  loop: "{{ enduro_pipelines }}"
  when:
    - enduro_pipelines|length > 0
    - enduro_create_pipeline_transfer_dir|bool
