---
- name: Download tctl binary to local folder
  become: false
  get_url:
    url: "https://github.com/temporalio/tctl/releases/download/v{{ tctl_version }}/tctl_{{ tctl_version }}_linux_amd64.tar.gz"
    dest: "/tmp/tctl_{{ tctl_version }}_linux_amd64.tar.gz"
    checksum: "sha256:{{ tctl_checksum_binaries }}"
    mode: '0644'
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: "Create tmp tctl directories"
  become: false
  file:
    path: "/tmp/tctl_{{ tctl_version }}_linux_amd64"
    state: directory
  delegate_to: localhost
  check_mode: false

- name: Unpack tctl binary
  become: false
  unarchive:
    src: "/tmp/tctl_{{ tctl_version }}_linux_amd64.tar.gz"
    dest: "/tmp/tctl_{{ tctl_version }}_linux_amd64"
    creates: "/tmp/tctl_{{ tctl_version }}_linux_amd64/tctl"
  delegate_to: localhost
  check_mode: false

- name: Propagate tctl binary
  copy:
    src: "/tmp/tctl_{{ tctl_version }}_linux_amd64/tctl"
    dest: "{{ tctl_binary_install_dir }}/tctl"
    mode: 0755
    owner: root
    group: root
  when: not ansible_check_mode
