---

- name: Create the enduro group
  group:
    name: "{{ enduro_system_group }}"
    state: present
    system: true
  when: enduro_create_system_user|bool

- name: Create the enduro user
  user:
    name: "{{ enduro_system_user }}"
    groups: "{{ enduro_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: true
    home: /var/lib/enduro
  when: enduro_create_system_user|bool

- name: "Add GPG key for rpm repo (RedHat)"
  rpm_key:
    key: "{{ enduro_rpm_gpg_key }}"
    state: present
  when:
    - enduro_rpm_gpg_check_enabled|bool

- name: Install enduro-am-worker package
  yum:
    name: "{{ enduro_am_worker_rpm_url }}"
    state: present
    disable_gpg_check: "{{ not enduro_rpm_gpg_check_enabled|bool }}"
