---
- name: "Discover tctl latest version"
  set_fact:
    tctl_version: "{{ (lookup('url', 'https://api.github.com/repos/temporalio/tctl/releases/latest', headers=_github_api_headers,
                            split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: tctl_version is version('0.0.0', '>=')
  retries: 10
  when:
    - tctl_version == "latest"

- name: "Get tctl checksum list from github"
  set_fact:
    _checksums: "{{ lookup('url', 'https://github.com/temporalio/tctl/releases/download/v' + tctl_version + '/checksums.txt', wantlist=True) | list }}"

- name: "Get Tctl checksum for linux amd64 binaries"
  set_fact:
    tctl_checksum_binaries: "{{ item.split(' ')[0] }}"
  with_items: "{{ _checksums }}"
  when:  "('linux_amd64.tar.gz') in item"
