---

- name: "Discover enduro latest version"
  set_fact:
    enduro_version: "{{ (lookup('url', 'https://api.github.com/repos/artefactual-labs/enduro/releases/latest', headers=_github_api_headers,
                            split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: enduro_version is version('0.0.0', '>=')
  retries: 10
  when:
    - enduro_version == "latest"

- name: "Get Enduro checksum list from github"
  set_fact:
    _checksums: "{{ lookup('url', 'https://github.com/artefactual-labs/enduro/releases/download/v' + enduro_version + '/checksums.txt', wantlist=True) | list }}"

- name: "Get Enduro checksum for amd64 architecture"
  set_fact:
    enduro_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ _checksums }}"
