---
- name: restart enduro
  become: true
  systemd:
    daemon_reload: true
    name: enduro
    state: restarted

- name: restart enduro-am-worker
  become: true
  systemd:
    daemon_reload: true
    name: enduro-am-worker
    state: restarted

- name: restart preprocessing-worker
  become: true
  systemd:
    daemon_reload: true
    name: preprocessing-worker
    state: restarted

- name: restart rsyslog
  become: true
  systemd:
    daemon_reload: true
    name: rsyslog
    state: restarted
  when: enduro_use_syslog|bool
